export const PID_FIELDS = [
    { label: 'Kp', suffix: 'kp', step: '0.1' },
    { label: 'Ki', suffix: 'ki', step: '0.01' },
    { label: 'Kd', suffix: 'kd', step: '0.001' },
    { label: 'Out Min', suffix: 'output_min', step: 'any' },
    { label: 'Out Max', suffix: 'output_max', step: 'any' },
    { label: 'ITerm Min', suffix: 'iterm_min', step: 'any' },
    { label: 'ITerm Max', suffix: 'iterm_max', step: 'any' }
];

export const GENERAL_CONFIG_FIELDS = [
    { label: 'Loop Int(ms)', id: 'mainLoop_interval_ms', step: '1', min: 1, max: 1000, section: 'mainLoop', key: 'interval_ms' },
    { label: 'IMU Alpha', id: 'imu_comp_filter_alpha', step: '0.001', min: 0, max: 1, section: 'imu', key: 'comp_filter_alpha' },
    { label: 'IMU Cal Samp', id: 'imu_calibration_samples', step: '100', min: 10, max: 10000, section: 'imu', key: 'calibration_samples' },
    { label: 'IMU I2C Hz', id: 'imu_i2c_freq_hz', step: '1000', min: 10000, max: 400000, section: 'imu', key: 'i2c_freq_hz' },
    { label: 'IMU FIFO Thr', id: 'imu_fifo_read_threshold', step: '1', min: 1, max: 240, section: 'imu', key: 'fifo_read_threshold' },
    { label: 'IMU Gyro X Off', id: 'imu_gyro_offset_x', step: '0.001', section: 'imu', key: 'gyro_offset_x' },
    { label: 'IMU Gyro Y Off', id: 'imu_gyro_offset_y', step: '0.001', section: 'imu', key: 'gyro_offset_y' },
    { label: 'IMU Gyro Z Off', id: 'imu_gyro_offset_z', step: '0.001', section: 'imu', key: 'gyro_offset_z' },
    { label: 'Joy Exp', id: 'control_joystick_exponent', step: '0.1', min: 0.1, max: 5.0, section: 'control', key: 'joystick_exponent' },
    { label: 'Max Tilt (deg)', id: 'control_max_target_pitch_offset_deg', step: '0.1', min: 0, max: 90, section: 'control', key: 'max_target_pitch_offset_deg' },
    { label: 'Yaw Control', id: 'control_yaw_control_enabled', type: 'checkbox', section: 'control', key: 'yaw_control_enabled' },
    { label: 'M Deadzone', id: 'motor_deadzone_duty', step: '1', min: 0, section: 'motor', key: 'deadzone_duty' },
    { label: 'Enc Gear Ratio', id: 'encoder_gear_ratio', step: '0.1', min: 0.1, max: 1000, section: 'encoder', key: 'gear_ratio' },
    { label: 'Enc Whl Diam mm', id: 'encoder_wheel_diameter_mm', step: '0.1', min: 1, max: 1000, section: 'encoder', key: 'wheel_diameter_mm' },
    { label: 'Enc Filter Alpha', id: 'encoder_speed_filter_alpha', step: '0.01', min: 0, max: 1, section: 'encoder', key: 'speed_filter_alpha' },
    { label: 'Tune Step Effort', id: 'pid_tuning_step_effort', step: '0.01', min: 0.01, max: 1, section: 'pid_tuning', key: 'step_effort' },
    { label: 'Tune Agg Effort', id: 'pid_tuning_max_effort', step: '0.01', min: 0.01, max: 1, section: 'pid_tuning', key: 'max_effort' },
    { label: 'Tune Step(ms)', id: 'pid_tuning_step_duration_ms', step: '100', min: 100, max: 10000, section: 'pid_tuning', key: 'step_duration_ms' },
    { label: 'Tune Rest(ms)', id: 'pid_tuning_rest_duration_ms', step: '100', min: 0, max: 10000, section: 'pid_tuning', key: 'rest_duration_ms' },
    { label: 'Tune Min Resp', id: 'pid_tuning_min_response_dps', step: '10', min: 1, max: 5000, section: 'pid_tuning', key: 'min_response_dps' },
    { label: 'Tune Max Speed', id: 'pid_tuning_max_speed_dps', step: '10', min: 1, max: 10000, section: 'pid_tuning', key: 'max_speed_dps' },
    { label: 'Tune Val Target', id: 'pid_tuning_validation_target_dps', step: '10', min: 1, max: 10000, section: 'pid_tuning', key: 'validation_target_dps' },
    { label: 'Tune Gain Scale', id: 'pid_tuning_gain_scale', step: '0.05', min: 0.05, max: 1, section: 'pid_tuning', key: 'gain_scale' },
    { label: 'Batt Max V', id: 'battery_voltage_max', step: '0.01', min: 0.1, max: 100, section: 'battery', key: 'voltage_max' },
    { label: 'Batt Min V', id: 'battery_voltage_min', step: '0.01', min: 0.1, section: 'battery', key: 'voltage_min' },
    { label: 'Batt Ratio', id: 'battery_voltage_divider_ratio', step: '0.001', min: 0.1, max: 100, section: 'battery', key: 'voltage_divider_ratio' },
    { label: 'Crit Batt Shutdown', id: 'battery_critical_battery_motor_shutdown_enabled', type: 'checkbox', section: 'battery', key: 'critical_battery_motor_shutdown_enabled' },
    { label: 'Wheelbase (m)', id: 'dimensions_wheelbase_m', step: '0.001', min: 0.01, max: 1.0, section: 'dimensions', key: 'wheelbase_m' },
    { label: 'Joy Deadzone', id: 'behavior_joystick_deadzone', step: '0.01', min: 0, max: 1, section: 'behavior', key: 'joystick_deadzone' },
    { label: 'Joy Timeout(ms)', id: 'behavior_joystick_timeout_ms', step: '10', min: 1, max: 10000, section: 'behavior', key: 'joystick_timeout_ms' },
    { label: 'Joy Max AngVel', id: 'behavior_max_target_angular_velocity_dps', step: '1', min: 1, max: 1000, section: 'behavior', key: 'max_target_angular_velocity_dps' },
    { label: 'Fall Thresh(deg)', id: 'behavior_fall_pitch_threshold_deg', step: '1', min: 10, max: 90, section: 'behavior', key: 'fall_pitch_threshold_deg' },
    { label: 'Fall Dura(ms)', id: 'behavior_fall_threshold_duration_ms', step: '10', min: 1, max: 10000, section: 'behavior', key: 'fall_threshold_duration_ms' },
    { label: 'AutoBal Thresh(deg)', id: 'behavior_auto_balance_pitch_threshold_deg', step: '0.1', min: 0, max: 30, section: 'behavior', key: 'auto_balance_pitch_threshold_deg' },
    { label: 'AutoBal Hold(ms)', id: 'behavior_auto_balance_hold_duration_ms', step: '100', min: 1, max: 60000, section: 'behavior', key: 'auto_balance_hold_duration_ms' },
    { label: 'Batt Samples', id: 'behavior_battery_oversampling_count', step: '1', min: 1, max: 1024, section: 'behavior', key: 'battery_oversampling_count' },
    { label: 'Batt Int(ms)', id: 'behavior_battery_read_interval_ms', step: '100', min: 100, max: 60000, section: 'behavior', key: 'battery_read_interval_ms' },
    { label: 'IMU I2C Fail Thr', id: 'behavior_imu_health_i2c_fail_threshold', step: '1', min: 1, max: 100, section: 'behavior', key: 'imu_health_i2c_fail_threshold' },
    { label: 'IMU NoData Thr', id: 'behavior_imu_health_no_data_threshold', step: '1', min: 1, max: 100, section: 'behavior', key: 'imu_health_no_data_threshold' },
    { label: 'IMU Timeout(ms)', id: 'behavior_imu_health_data_timeout_ms', step: '10', min: 1, max: 10000, section: 'behavior', key: 'imu_health_data_timeout_ms' },
    { label: 'Telem Buf Size', id: 'web_telemetry_buffer_size', step: '10', min: 1, max: 10000, section: 'web', key: 'telemetry_buffer_size' },
    { label: 'Max POST Size', id: 'web_max_config_post_size', step: '128', min: 512, max: 65536, section: 'web', key: 'max_config_post_size' }
];
