export const MAX_DATA_POINTS = 400;
// Keep graph latency below one control period batch during fast motion.
export const DATA_FETCH_INTERVAL_MS = 50;
export const STATE_FETCH_INTERVAL_MS = 1000;
export const JOYSTICK_SEND_INTERVAL_MS = 75;
export const WS_RECONNECT_DELAY_MS = 3000;

export const API_COMMAND_URL = '/api/command';
export const API_CONFIG_URL = '/api/config';
export const API_CONFIG_OPERATION_URL = '/api/config/operation';
export const API_STATE_URL = '/api/state';
export const API_DATA_URL = '/data';
export const API_OTA_URL = '/api/ota';
export const API_LOGS_URL = '/api/logs';

// Function to get WebSocket URL dynamically
export function getWsUrl() {
    const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
    return `${protocol}//${window.location.host}/ws`;
}

// Graphing constants
export const GRAPH_COLORS = ['#6f42c1', '#0d6efd', '#dc3545', '#198754', '#ffc107', '#fd7e14', '#20c997', '#0dcaf0']; // Added color for yaw
export const Y_SPEED_RANGE_DPS = 800;
export const Y_ANGLE_RANGE_DEG = 90;
export const Y_EFFORT_RANGE = 1.0;
export const Y_YAW_ANGLE_RANGE_DEG = 180;
export const Y_YAWRATE_RANGE_DPS = 180;

export const TELEMETRY_FORMAT_VERSION = 4;
export const TELEMETRY_IMU_VALID_INDEX = 12;
export const TELEMETRY_IMU_AGE_INDEX = 13;
export const TELEMETRY_IMU_GENERATION_INDEX = 14;
export const TELEMETRY_V4_MIN_LENGTH = 70;
export const TELEMETRY_V4 = Object.freeze({
    TIMESTAMP_US: 18,
    STRATEGY_ID: 19,
    LOOP_MODE: 20,
    STRATEGY_REVISION: 21,
    CONFIG_REVISION: 22,
    COMMAND_SESSION_ID: 23,
    CONTROL_GENERATION: 24,
    ODOMETRY_GENERATION: 25,
    ODOMETRY_SEQUENCE: 26,
    PHASE: 27,
    CONTROL_VALID: 28,
    TARGET_PITCH_VALID: 29,
    TARGET_PITCH_CLAMPED: 30,
    TARGET_PITCH_RATE_LIMITED: 31,
    POSITION_TARGET_VALID: 32,
    POSITION_HOLD_ACTIVE: 33,
    SYNCHRONIZATION_TARGET_VALID: 34,
    VELOCITY_LOOP_ENABLED: 35,
    POSITION_LOOP_ENABLED: 36,
    SYNCHRONIZATION_ENABLED: 37,
    MOTION_COMMAND_VALID: 38,
    MOTION_COMMAND_FRESH: 39,
    VELOCITY_FEEDBACK_VALID: 40,
    VELOCITY_TARGET_CLAMPED: 41,
    VELOCITY_OUTPUT_SATURATED: 42,
    VELOCITY_ANTI_WINDUP: 43,
    PITCH_PID_SATURATED: 44,
    BALANCE_SATURATED: 45,
    MIXER_SATURATED: 46,
    SYNC_LIMITED: 47,
    MOTION_REQUEST_LIMITED: 48,
    PHASE_REASON: 49,
    TARGET_PITCH_DEG: 50,
    TARGET_VELOCITY_MPS: 51,
    COMMAND_VELOCITY_MPS: 52,
    MEASURED_VELOCITY_MPS: 53,
    HOLD_VELOCITY_REQUEST_MPS: 54,
    HOLD_VELOCITY_TARGET_MPS: 55,
    POSITION_M: 56,
    HOLD_POSITION_M: 57,
    POSITION_ERROR_M: 58,
    DISTANCE_DIFFERENCE_M: 59,
    DISTANCE_DIFFERENCE_TARGET_M: 60,
    SYNC_VELOCITY_DIFFERENCE_MPS: 61,
    REQUESTED_BALANCE_EFFORT: 62,
    BALANCE_EFFORT: 63,
    REQUESTED_SYNC_EFFORT: 64,
    SYNC_EFFORT: 65,
    LEFT_EFFORT: 66,
    RIGHT_EFFORT: 67,
    YAW_TARGET_VALID: 68,
    YAW_CONTROL_AVAILABLE: 69,
    MOTOR_COMMIT_ATTEMPTED: 70,
    MOTOR_COMMIT_SUCCEEDED: 71,
    MOTOR_COMMIT_RESULT: 72,
    FAULT_REASON: 73,
    FAULT_LATCHED: 74,
    IMU_SAMPLE_SEQUENCE: 75,
    CONTROL_STEP_COST_US: 76,
    CONTROL_STEP_LATE: 77
});
